### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by als-creator** [mrzlab630/chrome-extension-YoK#3]
Failed to fetch
другие расширения для кинопоиска тоже не работают, наверно на сайте что-то поменяли

**Comment by mrzlab630** [comment]
ошибка 523 на стороне торрент агрегатора 4h0y.github.io
подожду некоторое время если не решат. буду искать другой.

**Comment by als-creator** [comment]
они донат за просмотр просят, вот агрегатор https://kinobox.tv

**Comment by mrzlab630** [comment]
изменил источник на https://kinobox.tv.
так же отправил на модерацию в магазин chrome

**Comment by als-creator** [comment]
уже работает расширение
